# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: LZ
email: luis.zuniga@yale.edu
description: >- # this means to ignore newlines until "baseurl:"
"Luis Zuñiga's personal website"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.lfzuniga.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: lfzuniga_
github_username: lfzuniga

# Even though you can edit the color in the stlye.scss file, it's easier to change it here - LZ
minima:
  skin: "dark" #  "dark", "classic", 
  date_format: "%Y-%m-%d"
  social_links:
    - { platform: github, user_url: "https://github.com/lfzuniga" }
    - { platform: x, user_url: "https://twitter.com/lfzuniga_" }
    - { platform: linkedin, user_url: "https://linkedin.com/in/lfzuniga" }
# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
header_pages:
 # - projects.markdown
  #  - writing.markdown could add back once I have a better query function or something like that
  - currently.markdown

author:
  name: Luis Zuñiga

# working with the collections part
collections:
  projects:
    output: true
    permalink: /:collection/:path/
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

